server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_a97b1ad5b10f
    token: b8b6
    app-id: wxc16ffef8ada4e8e2
    app-secret: 7e23cb0541935a6f040127df737858fe
    template_id: 11aimp56v9ZQxRmdJn4eSm6gBP-YWJILErs-pj5TMyE

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000141627098
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDH6a6xXXsLHl4J5NfyfLnU7dSWVgyid+KOtJryH7jageJb3Gh8jwqF4ivlUhUCqVrYyoGO0y878j80SzHRWlrQy/wvwUGWKNalcU5r5uvU6j3kfC0bybFV+oV2/zdZ7wUKyMk9+/yAZrecc1QgFZu6e5OjrFwVRuW3R49NtQh5cnzrIAR/cTY6dzed6MFu1fyMhnkupRhng9OeuJ2JsJ6OHhI9n2Wq4uSWYMuAa2GxNCsTpbY4Ru7exvKjm8atTp5U8QtR8xgN+FCPD7FWVUR/RUAd2v2DLi+z18OHwr0sEjQ1X3QY2+GSSA7RNeuIaY9yFFxuVYJmhSjDBY7dCaixAgMBAAECggEAfweyhenMwefuAYN05RT0UKU/rLfJF4PuZpfEzY3yvIZD+/M2Qc/y89gf5Hwf9az/mTo00TjIjuMD3orZgRpVEtBL01yN/Ii+vCofltkJiiW+Zm2xjDLBiMzD+jV6Sp9jKNMlbUmtzTl3+uYd0rVoWzsjOaHQcYS3e5rxKIOceu5wsI5dHH988/Sjv3D/q0J2nTbxmMs2S2FQLVgWlSwXLjccDGQ3A75MMvtEKuCvtD76s2hKVOfakNi8FjlzGRGrjHsuD3tymfC2UH1k23QuW/ZRsNLynvYer5prVvnycCf82jHKZOlpp2D6DLoBJY1eMZODoZzUzg59Ok4OdSCvMQKBgQD0RXVoSg1q8fg/9lv9p3sOTQphdtN1OHxbL9G1V0CMnVTOYUPB8gcMprOLF314/cTyJtSkIK1JBGzFvK/SnmaGAhLPYBuklNaNiGyjmGPIvlKWhBNc04VMtWnF3irRjq7HQ9RwhGWARboUjom0QCxugpOldfCrZvE4rds8YRKsLwKBgQDRgvoGDFiyAjv83e/di/u70TEaNAPOLLITAqIhiB2FeMzwh8shpQHPUnSgo7ef1jyM1XzRGFlZkofuNJ1bihg8ujNShqWxprNBbrm9y/PuY3R1rFdB9MahNOm03o0RWLhNSJkGvD/M7AAjJGDWhpT88XWeFDOfI1wZiRWD0MdhHwKBgQDOwbwO+h9BVm56NVzH5usRv8P5m0qA/b7EsEUg6SmJ2+Hcjhd8IhA1dSSjps5diu8YyCVUhxQlqckn1f48mDbPVxH01bSQKiswwTizgFl1oSLmpAR/ncpGk4dkJBi6J7tojtFSK75+RIasv7lvCKKTJ5MxihKcAhZLk1zuTnwvoQKBgBElCbbC/eMbQbNwqfdURDZbaQw+42zUxYG+vmvGCrxoZUTtp9bJ/PrtQXP/0b/3tR7FPaCSwIUO86avkYzzIQafKiH/uMFv5c1d9T8t2HlSlC4o+z7/e92nSdSuPZcEzpgsb7FYaFQpn91AVdhYTQrh64ETICJOr3O7fxI5XId7AoGAGqYDLdCZ+X1tVztztPKbrx3J2vM1tozK6JIkRZ5NyG/2LXjecl1TCvZHbZd3ibVj7oHDjflUcULfXhIhmq0dk7ZCmffOhndc+x2MO5++5alSxJ7LiaU5Y6ZyoFrOi1n981MaVpALMXW2HuZ6AH1YLH1PsU4op/AJVyBT4qhpz8Y=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTIR+4IwpBhk6rUZhGmfaVgKPHZ3XLd9PyBB6PUxHKKsWRa91AHo+WiJWvg8Rxi5SZnYrjBwbbz1Wtolht6lKfB8OXnWAFhVtOOfUycRwdTvuwh+A7PIBRYg529/oF7x4v1RtzLFopoLSrKGKNdx78InPUqButN1d8aIzcn2YWhIyu2VSzRkNztUliZXBuc7ESonwmzQB2Wd5SX5Uw6cPPm4UHhbMvcqKHoGFeJ0X1SopF18fpsL+LOfdrTl/DI1tCtDHVOoPLg+SEmzPcCIyphXocSXWFrCIjMHcRTcVmMLiPu7K1x4Ro3l+pDRCnuNm97FV1tMyb6Of6TMqDWwnwIDAQAB
  notify_url: http://xyf-s-pay-mall.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml